-- MySQL Script generated by MySQL Workbench
-- Tue May  3 23:15:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema datacustodian
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema datacustodian
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datacustodian` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `datacustodian` ;

-- -----------------------------------------------------
-- Table `datacustodian`.`application_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`application_information` (
                                                                         `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                         `kind` VARCHAR(255) NULL DEFAULT NULL,
    `description` VARCHAR(255) NULL DEFAULT NULL,
    `published` DATETIME NULL DEFAULT NULL,
    `self_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `self_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `updated` DATETIME NULL DEFAULT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `authorizationServerAuthorizationEndpoint` VARCHAR(255) NULL DEFAULT NULL,
    `authorizationServerRegistrationEndpoint` VARCHAR(255) NULL DEFAULT NULL,
    `authorizationServerTokenEndpoint` VARCHAR(255) NULL DEFAULT NULL,
    `authorizationServerUri` VARCHAR(255) NULL DEFAULT NULL,
    `clientId` VARCHAR(64) NOT NULL,
    `clientIdIssuedAt` BIGINT NULL DEFAULT NULL,
    `clientName` VARCHAR(255) NULL DEFAULT NULL,
    `clientSecret` VARCHAR(255) NULL DEFAULT NULL,
    `clientSecretExpiresAt` BIGINT NULL DEFAULT NULL,
    `clientUri` VARCHAR(255) NULL DEFAULT NULL,
    `contacts` TINYBLOB NULL DEFAULT NULL,
    `dataCustodianApplicationStatus` VARCHAR(255) NULL DEFAULT NULL,
    `dataCustodianBulkRequestURI` VARCHAR(255) NULL DEFAULT NULL,
    `dataCustodianDefaultBatchResource` VARCHAR(255) NULL DEFAULT NULL,
    `dataCustodianDefaultSubscriptionResource` VARCHAR(255) NULL DEFAULT NULL,
    `dataCustodianId` VARCHAR(64) NULL DEFAULT NULL,
    `dataCustodianResourceEndpoint` VARCHAR(255) NULL DEFAULT NULL,
    `dataCustodianThirdPartySelectionScreenURI` VARCHAR(255) NULL DEFAULT NULL,
    `logoUri` VARCHAR(255) NULL DEFAULT NULL,
    `policyUri` VARCHAR(255) NULL DEFAULT NULL,
    `redirectUri` VARCHAR(255) NULL DEFAULT NULL,
    `registrationAccessToken` VARCHAR(255) NULL DEFAULT NULL,
    `registrationClientUri` VARCHAR(255) NULL DEFAULT NULL,
    `responseTypes` INT NULL DEFAULT NULL,
    `softwareId` VARCHAR(255) NULL DEFAULT NULL,
    `softwareVersion` VARCHAR(255) NULL DEFAULT NULL,
    `thirdPartyApplicationDescription` VARCHAR(255) NULL DEFAULT NULL,
    `thirdPartyApplicationName` VARCHAR(64) NOT NULL,
    `thirdPartyApplicationStatus` VARCHAR(255) NULL DEFAULT NULL,
    `thirdPartyApplicationType` VARCHAR(255) NULL DEFAULT NULL,
    `thirdPartyApplicationUse` VARCHAR(255) NULL DEFAULT NULL,
    `thirdPartyDataCustodianSelectionScreenURI` VARCHAR(255) NULL DEFAULT NULL,
    `thirdPartyLoginScreenURI` VARCHAR(255) NULL DEFAULT NULL,
    `thirdPartyNotifyUri` VARCHAR(255) NULL DEFAULT NULL,
    `thirdPartyPhone` VARCHAR(255) NULL DEFAULT NULL,
    `thirdPartyScopeSelectionScreenURI` VARCHAR(255) NULL DEFAULT NULL,
    `thirdPartyUserPortalScreenURI` VARCHAR(255) NULL DEFAULT NULL,
    `tokenEndpointAuthMethod` VARCHAR(255) NULL DEFAULT NULL,
    `tosUri` VARCHAR(255) NULL DEFAULT NULL,
    `dataCustodianScopeSelectionScreenURI` VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `uuid`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 6
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`application_information_grant_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`application_information_grant_types` (
                                                                                     `application_information_id` BIGINT NOT NULL,
                                                                                     `grantTypes` VARCHAR(255) NULL DEFAULT NULL,
    INDEX `FK_61a6f8b0091946139543874e559` (`application_information_id` ASC) VISIBLE,
    CONSTRAINT `FK_61a6f8b0091946139543874e559`
    FOREIGN KEY (`application_information_id`)
    REFERENCES `datacustodian`.`application_information` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`application_information_scopes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`application_information_scopes` (
                                                                                `application_information_id` BIGINT NOT NULL,
                                                                                `scope` VARCHAR(255) NULL DEFAULT NULL,
    INDEX `FK_61a6f8b0091946139543874d559` (`application_information_id` ASC) VISIBLE,
    CONSTRAINT `FK_61a6f8b0091946139543874d559`
    FOREIGN KEY (`application_information_id`)
    REFERENCES `datacustodian`.`application_information` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`authorizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`authorizations` (
                                                                `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                `description` VARCHAR(255) NULL DEFAULT NULL,
    `published` DATETIME NULL DEFAULT NULL,
    `self_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `self_link_rel` VARCHAR(255) NULL DEFAULT 'self',
    `up_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_rel` VARCHAR(255) NULL DEFAULT 'up',
    `updated` DATETIME NULL DEFAULT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `access_token` VARCHAR(255) NULL DEFAULT NULL,
    `authorization_uri` VARCHAR(255) NULL DEFAULT NULL,
    `ap_duration` BIGINT NULL DEFAULT NULL,
    `ap_start` BIGINT NULL DEFAULT NULL,
    `code` VARCHAR(255) NULL DEFAULT NULL,
    `error` INT NULL DEFAULT NULL,
    `errorDescription` VARCHAR(255) NULL DEFAULT NULL,
    `errorUri` VARCHAR(255) NULL DEFAULT NULL,
    `expiresIn` BIGINT NULL DEFAULT NULL,
    `grantType` INT NULL DEFAULT NULL,
    `pp_duration` BIGINT NULL DEFAULT NULL,
    `pp_start` BIGINT NULL DEFAULT NULL,
    `refreshToken` VARCHAR(255) NULL DEFAULT NULL,
    `resourceURI` VARCHAR(255) NULL DEFAULT NULL,
    `responseType` INT NULL DEFAULT NULL,
    `scope` VARCHAR(255) NULL DEFAULT NULL,
    `state` VARCHAR(255) NULL DEFAULT NULL,
    `status` VARCHAR(255) NULL DEFAULT NULL,
    `third_party` VARCHAR(255) NULL DEFAULT NULL,
    `tokenType` INT NULL DEFAULT NULL,
    `application_information_id` BIGINT NULL DEFAULT NULL,
    `retail_customer_id` BIGINT NULL DEFAULT NULL,
    `subscription_id` BIGINT NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `uuid`),
    INDEX `FK_d0761ae9d2dd44c49867ac4ec4b` (`application_information_id` ASC) VISIBLE,
    INDEX `FK_a4fccef421a14e0ead5c1b9753d` (`retail_customer_id` ASC) VISIBLE,
    INDEX `FK_subscriptionkey` (`subscription_id` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 38
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`retail_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`retail_customers` (
                                                                  `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                  `description` VARCHAR(255) NULL DEFAULT NULL,
    `published` DATETIME NULL DEFAULT NULL,
    `self_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `self_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `updated` DATETIME NULL DEFAULT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `enabled` BIT(1) NOT NULL,
    `first_name` VARCHAR(30) NOT NULL,
    `last_name` VARCHAR(30) NOT NULL,
    `password` VARCHAR(100) NULL DEFAULT NULL,
    `role` VARCHAR(255) NOT NULL,
    `username` VARCHAR(30) NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `uuid`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 15
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`subscriptions` (
                                                               `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                               `description` VARCHAR(255) NULL DEFAULT NULL,
    `published` DATETIME NULL DEFAULT NULL,
    `self_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `self_link_rel` VARCHAR(255) NULL DEFAULT 'self',
    `up_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_rel` VARCHAR(255) NULL DEFAULT 'up',
    `updated` DATETIME NULL DEFAULT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `hashedId` VARCHAR(255) NULL DEFAULT NULL,
    `lastUpdate` DATETIME NULL DEFAULT NULL,
    `applicationInformation_id` BIGINT NOT NULL,
    `authorization_id` BIGINT NULL DEFAULT NULL,
    `retail_customer_id` BIGINT NOT NULL,
    `usagepoint_id` INT NULL,
    PRIMARY KEY (`id`, `uuid`),
    INDEX `FK_a027c87418ce4d7abbde7ee5eec` (`applicationInformation_id` ASC) VISIBLE,
    INDEX `FK_a68a2938cbc142c3b82f57cb4b1` (`authorization_id` ASC) VISIBLE,
    INDEX `FK_e38a940ce8ed4d8983d1d5dac6e` (`retail_customer_id` ASC) VISIBLE,
    CONSTRAINT `FK_a027c87418ce4d7abbde7ee5eec`
    FOREIGN KEY (`applicationInformation_id`)
    REFERENCES `datacustodian`.`application_information` (`id`),
    CONSTRAINT `FK_e38a940ce8ed4d8983d1d5dac6e`
    FOREIGN KEY (`retail_customer_id`)
    REFERENCES `datacustodian`.`retail_customers` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 38
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`time_configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`time_configurations` (
                                                                     `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                     `description` VARCHAR(255) NULL DEFAULT NULL,
    `published` DATETIME NULL DEFAULT NULL,
    `self_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `self_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `updated` DATETIME NULL DEFAULT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `dstEndRule` TINYBLOB NULL DEFAULT NULL,
    `dstOffset` BIGINT NOT NULL,
    `dstStartRule` TINYBLOB NULL DEFAULT NULL,
    `tzOffset` BIGINT NOT NULL,
    PRIMARY KEY (`id`, `uuid`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`service_delivery_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`service_delivery_points` (
                                                                         `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                         `customerAgreement` VARCHAR(255) NULL DEFAULT NULL,
    `name` VARCHAR(255) NULL DEFAULT NULL,
    `tariffProfile` VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`usage_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`usage_points` (
                                                              `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                              `description` VARCHAR(255) NULL DEFAULT NULL,
    `published` DATETIME NULL DEFAULT NULL,
    `self_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `self_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `updated` DATETIME NULL DEFAULT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `roleFlags` TINYBLOB NULL DEFAULT NULL,
    `status` SMALLINT NULL DEFAULT NULL,
    `uri` VARCHAR(255) NULL DEFAULT NULL,
    `localTimeParameters_id` BIGINT NULL DEFAULT NULL,
    `retail_customer_id` BIGINT NULL DEFAULT NULL,
    `serviceCategory_kind` BIGINT NOT NULL,
    `serviceDeliveryPoint_id` BIGINT NULL DEFAULT NULL,
    `subscription_id` BIGINT NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `UK_d3b5c06a4b994ad8906ead9757f` (`uuid` ASC) VISIBLE,
    INDEX `FK_9fa5cbe1eaeb4dbfb7209cb0213` (`localTimeParameters_id` ASC) VISIBLE,
    INDEX `FK_41107ba4248e4bf79b62c405385` (`retail_customer_id` ASC) VISIBLE,
    INDEX `FK_c3909436c6934c8bb14da2bb93b` (`serviceDeliveryPoint_id` ASC) VISIBLE,
    INDEX `FK_53bcef9479ff4522b63a46e018c` (`subscription_id` ASC) VISIBLE,
    CONSTRAINT `FK_41107ba4248e4bf79b62c405385`
    FOREIGN KEY (`retail_customer_id`)
    REFERENCES `datacustodian`.`retail_customers` (`id`),
    CONSTRAINT `FK_53bcef9479ff4522b63a46e018c`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `datacustodian`.`subscriptions` (`id`),
    CONSTRAINT `FK_9fa5cbe1eaeb4dbfb7209cb0213`
    FOREIGN KEY (`localTimeParameters_id`)
    REFERENCES `datacustodian`.`time_configurations` (`id`),
    CONSTRAINT `FK_c3909436c6934c8bb14da2bb93b`
    FOREIGN KEY (`serviceDeliveryPoint_id`)
    REFERENCES `datacustodian`.`service_delivery_points` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 3
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`electric_power_quality_summaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`electric_power_quality_summaries` (
                                                                                  `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                                  `description` VARCHAR(255) NULL DEFAULT NULL,
    `published` DATETIME NULL DEFAULT NULL,
    `self_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `self_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `updated` DATETIME NULL DEFAULT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `flickerPlt` BIGINT NULL DEFAULT NULL,
    `flickerPst` BIGINT NULL DEFAULT NULL,
    `harmonicVoltage` BIGINT NULL DEFAULT NULL,
    `longInterruptions` BIGINT NULL DEFAULT NULL,
    `mainsVoltage` BIGINT NULL DEFAULT NULL,
    `measurementProtocol` SMALLINT NULL DEFAULT NULL,
    `powerFrequency` BIGINT NULL DEFAULT NULL,
    `rapidVoltageChanges` BIGINT NULL DEFAULT NULL,
    `shortInterruptions` BIGINT NULL DEFAULT NULL,
    `duration` BIGINT NULL DEFAULT NULL,
    `start` BIGINT NULL DEFAULT NULL,
    `supplyVoltageDips` BIGINT NULL DEFAULT NULL,
    `supplyVoltageImbalance` BIGINT NULL DEFAULT NULL,
    `supplyVoltageVariations` BIGINT NULL DEFAULT NULL,
    `tempOvervoltage` BIGINT NULL DEFAULT NULL,
    `usage_point_id` BIGINT NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `uuid`),
    INDEX `FK_804ec1c7cfd4488a8fa95388b74` (`usage_point_id` ASC) VISIBLE,
    CONSTRAINT `FK_804ec1c7cfd4488a8fa95388b74`
    FOREIGN KEY (`usage_point_id`)
    REFERENCES `datacustodian`.`usage_points` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`electric_power_usage_summaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`electric_power_usage_summaries` (
                                                                                `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                                `description` VARCHAR(255) NULL DEFAULT NULL,
    `published` DATETIME NULL DEFAULT NULL,
    `self_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `self_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `updated` DATETIME NULL DEFAULT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `billLastPeriod` BIGINT NULL DEFAULT NULL,
    `billToDate` BIGINT NULL DEFAULT NULL,
    `billingPeriod_duration` BIGINT NULL DEFAULT NULL,
    `billingPeriod_start` BIGINT NULL DEFAULT NULL,
    `costAdditionalLastPeriod` BIGINT NULL DEFAULT NULL,
    `currency` VARCHAR(255) NULL DEFAULT NULL,
    `currentBillingPeriodOverAllConsumption_powerOfTenMultiplier` VARCHAR(255) NULL DEFAULT NULL,
    `currentBillingPeriodOverAllConsumption_timeStamp` BIGINT NULL DEFAULT NULL,
    `currentBillingPeriodOverAllConsumption_uom` VARCHAR(255) NULL DEFAULT NULL,
    `currentBillingPeriodOverAllConsumption_value` BIGINT NULL DEFAULT NULL,
    `currentDayLastYearNetConsumption_powerOfTenMultiplier` VARCHAR(255) NULL DEFAULT NULL,
    `currentDayLastYearNetConsumption_timeStamp` BIGINT NULL DEFAULT NULL,
    `currentDayLastYearNetConsumption_uom` VARCHAR(255) NULL DEFAULT NULL,
    `currentDayLastYearNetConsumption_value` BIGINT NULL DEFAULT NULL,
    `currentDayNetConsumption_powerOfTenMultiplier` VARCHAR(255) NULL DEFAULT NULL,
    `currentDayNetConsumption_timeStamp` BIGINT NULL DEFAULT NULL,
    `currentDayNetConsumption_uom` VARCHAR(255) NULL DEFAULT NULL,
    `currentDayNetConsumption_value` BIGINT NULL DEFAULT NULL,
    `currentDayOverallConsumption_powerOfTenMultiplier` VARCHAR(255) NULL DEFAULT NULL,
    `currentDayOverallConsumption_timeStamp` BIGINT NULL DEFAULT NULL,
    `currentDayOverallConsumption_uom` VARCHAR(255) NULL DEFAULT NULL,
    `currentDayOverallConsumption_value` BIGINT NULL DEFAULT NULL,
    `overallConsumptionLastPeriod_powerOfTenMultiplier` VARCHAR(255) NULL DEFAULT NULL,
    `overallConsumptionLastPeriod_timeStamp` BIGINT NULL DEFAULT NULL,
    `overallConsumptionLastPeriod_uom` VARCHAR(255) NULL DEFAULT NULL,
    `overallConsumptionLastPeriod_value` BIGINT NULL DEFAULT NULL,
    `peakDemand_powerOfTenMultiplier` VARCHAR(255) NULL DEFAULT NULL,
    `peakDemand_timeStamp` BIGINT NULL DEFAULT NULL,
    `peakDemand_uom` VARCHAR(255) NULL DEFAULT NULL,
    `peakDemand_value` BIGINT NULL DEFAULT NULL,
    `previousDayLastYearOverallConsumption_powerOfTenMultiplier` VARCHAR(255) NULL DEFAULT NULL,
    `previousDayLastYearOverallConsumption_timeStamp` BIGINT NULL DEFAULT NULL,
    `previousDayLastYearOverallConsumption_uom` VARCHAR(255) NULL DEFAULT NULL,
    `previousDayLastYearOverallConsumption_value` BIGINT NULL DEFAULT NULL,
    `previousDayNetConsumption_powerOfTenMultiplier` VARCHAR(255) NULL DEFAULT NULL,
    `previousDayNetConsumption_timeStamp` BIGINT NULL DEFAULT NULL,
    `previousDayNetConsumption_uom` VARCHAR(255) NULL DEFAULT NULL,
    `previousDayNetConsumption_value` BIGINT NULL DEFAULT NULL,
    `previousDayOverallConsumption_powerOfTenMultiplier` VARCHAR(255) NULL DEFAULT NULL,
    `previousDayOverallConsumption_timeStamp` BIGINT NULL DEFAULT NULL,
    `previousDayOverallConsumption_uom` VARCHAR(255) NULL DEFAULT NULL,
    `previousDayOverallConsumption_value` BIGINT NULL DEFAULT NULL,
    `qualityOfReading` VARCHAR(255) NULL DEFAULT NULL,
    `ratchetDemand_powerOfTenMultiplier` VARCHAR(255) NULL DEFAULT NULL,
    `ratchetDemand_timeStamp` BIGINT NULL DEFAULT NULL,
    `ratchetDemand_uom` VARCHAR(255) NULL DEFAULT NULL,
    `ratchetDemand_value` BIGINT NULL DEFAULT NULL,
    `ratchetDemandPeriod_duration` BIGINT NULL DEFAULT NULL,
    `ratchetDemandPeriod_start` BIGINT NULL DEFAULT NULL,
    `statusTimeStamp` BIGINT NOT NULL,
    `usage_point_id` BIGINT NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `uuid`),
    INDEX `FK_73bd63f6333f44ff8c7f628f79d` (`usage_point_id` ASC) VISIBLE,
    CONSTRAINT `FK_73bd63f6333f44ff8c7f628f79d`
    FOREIGN KEY (`usage_point_id`)
    REFERENCES `datacustodian`.`usage_points` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`reading_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`reading_types` (
                                                               `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                               `description` VARCHAR(255) NULL DEFAULT NULL,
    `published` DATETIME NULL DEFAULT NULL,
    `self_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `self_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `updated` DATETIME NULL DEFAULT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `accumulationBehaviour` VARCHAR(255) NULL DEFAULT NULL,
    `rational_denominator` DECIMAL(19,2) NULL DEFAULT NULL,
    `rational_numerator` DECIMAL(19,2) NULL DEFAULT NULL,
    `commodity` VARCHAR(255) NULL DEFAULT NULL,
    `consumptionTier` VARCHAR(255) NULL DEFAULT NULL,
    `cpp` VARCHAR(255) NULL DEFAULT NULL,
    `currency` VARCHAR(255) NULL DEFAULT NULL,
    `dataQualifier` VARCHAR(255) NULL DEFAULT NULL,
    `defaultQuality` VARCHAR(255) NULL DEFAULT NULL,
    `flowDirection` VARCHAR(255) NULL DEFAULT NULL,
    `interharmonic_denominator` DECIMAL(19,2) NULL DEFAULT NULL,
    `interharmonic_numerator` DECIMAL(19,2) NULL DEFAULT NULL,
    `intervalLength` BIGINT NULL DEFAULT NULL,
    `kind` VARCHAR(255) NULL DEFAULT NULL,
    `measuringPeriod` VARCHAR(255) NULL DEFAULT NULL,
    `phase` VARCHAR(255) NULL DEFAULT NULL,
    `powerOfTenMultiplier` VARCHAR(255) NULL DEFAULT NULL,
    `timeAttribute` VARCHAR(255) NULL DEFAULT NULL,
    `tou` VARCHAR(255) NULL DEFAULT NULL,
    `uom` VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `uuid`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`meter_readings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`meter_readings` (
                                                                `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                `description` VARCHAR(255) NULL DEFAULT NULL,
    `published` DATETIME NULL DEFAULT NULL,
    `self_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `self_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `updated` DATETIME NULL DEFAULT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `reading_type_id` BIGINT NULL DEFAULT NULL,
    `usage_point_id` BIGINT NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `uuid`),
    INDEX `FK_67563dc6050e46ba9fcbc86b721` (`reading_type_id` ASC) VISIBLE,
    INDEX `FK_8eaf32259169401e8cae99a5891` (`usage_point_id` ASC) VISIBLE,
    CONSTRAINT `FK_67563dc6050e46ba9fcbc86b721`
    FOREIGN KEY (`reading_type_id`)
    REFERENCES `datacustodian`.`reading_types` (`id`),
    CONSTRAINT `FK_8eaf32259169401e8cae99a5891`
    FOREIGN KEY (`usage_point_id`)
    REFERENCES `datacustodian`.`usage_points` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`interval_blocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`interval_blocks` (
                                                                 `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                 `description` VARCHAR(255) NULL DEFAULT NULL,
    `published` DATETIME NULL DEFAULT NULL,
    `self_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `self_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_href` VARCHAR(255) NULL DEFAULT NULL,
    `up_link_rel` VARCHAR(255) NULL DEFAULT NULL,
    `updated` DATETIME NULL DEFAULT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `duration` BIGINT NULL DEFAULT NULL,
    `start` BIGINT NULL DEFAULT NULL,
    `meter_reading_id` BIGINT NULL DEFAULT NULL,
    PRIMARY KEY (`id`, `uuid`),
    INDEX `FK_23dcffa0baa44ffb817767d815f` (`meter_reading_id` ASC) VISIBLE,
    CONSTRAINT `FK_23dcffa0baa44ffb817767d815f`
    FOREIGN KEY (`meter_reading_id`)
    REFERENCES `datacustodian`.`meter_readings` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 15
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`interval_readings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`interval_readings` (
                                                                   `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                   `cost` BIGINT NULL DEFAULT NULL,
                                                                   `duration` BIGINT NULL DEFAULT NULL,
                                                                   `start` BIGINT NULL DEFAULT NULL,
                                                                   `value` BIGINT NULL DEFAULT NULL,
                                                                   `interval_block_id` BIGINT NULL DEFAULT NULL,
                                                                   `consumptionTier` BIGINT NULL DEFAULT NULL,
                                                                   `tou` BIGINT NULL DEFAULT NULL,
                                                                   `cpp` BIGINT NULL DEFAULT NULL,
                                                                   PRIMARY KEY (`id`),
    INDEX `FK_982b1bcd359b47fcb5823a43d21` (`interval_block_id` ASC) VISIBLE,
    CONSTRAINT `FK_982b1bcd359b47fcb5823a43d21`
    FOREIGN KEY (`interval_block_id`)
    REFERENCES `datacustodian`.`interval_blocks` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 2681
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`line_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`line_item` (
                                                           `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                           `amount` BIGINT NOT NULL,
                                                           `dateTime` BIGINT NOT NULL,
                                                           `note` VARCHAR(255) NULL DEFAULT NULL,
    `rounding` BIGINT NULL DEFAULT NULL,
    `electric_power_usage_summary_id` BIGINT NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `FK_5910ba965b7e41cd9bbe7949fbb` (`electric_power_usage_summary_id` ASC) VISIBLE,
    CONSTRAINT `FK_5910ba965b7e41cd9bbe7949fbb`
    FOREIGN KEY (`electric_power_usage_summary_id`)
    REFERENCES `datacustodian`.`electric_power_usage_summaries` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`reading_qualities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`reading_qualities` (
                                                                   `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                   `quality` VARCHAR(255) NULL DEFAULT NULL,
    `interval_reading_id` BIGINT NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `FK_11d630a57d684f26894e1cd6aa6` (`interval_reading_id` ASC) VISIBLE,
    CONSTRAINT `FK_11d630a57d684f26894e1cd6aa6`
    FOREIGN KEY (`interval_reading_id`)
    REFERENCES `datacustodian`.`interval_readings` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 5
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`reading_types_meter_readings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`reading_types_meter_readings` (
                                                                              `reading_types_id` BIGINT NOT NULL,
                                                                              `meterReadings_id` BIGINT NOT NULL,
                                                                              UNIQUE INDEX `UK_47a670721527488b84a5a98d629` (`meterReadings_id` ASC) VISIBLE,
    INDEX `FK_041b1404ae52437480cb75e6966` (`meterReadings_id` ASC) VISIBLE,
    INDEX `FK_5268261ff37f4147a4d1250213f` (`reading_types_id` ASC) VISIBLE,
    CONSTRAINT `FK_041b1404ae52437480cb75e6966`
    FOREIGN KEY (`meterReadings_id`)
    REFERENCES `datacustodian`.`meter_readings` (`id`),
    CONSTRAINT `FK_5268261ff37f4147a4d1250213f`
    FOREIGN KEY (`reading_types_id`)
    REFERENCES `datacustodian`.`reading_types` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `datacustodian`.`resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datacustodian`.`resources` (
                                                           `id` BIGINT NOT NULL,
                                                           `uri` VARCHAR(255) NULL DEFAULT NULL)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
