-- MySQL Script generated by MySQL Workbench
-- Tue May  3 23:16:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Status` (
    `value` VARCHAR(256) NULL,
    `dateTime` DATETIME NULL,
    `remark` VARCHAR(256) NULL,
    `reason` VARCHAR(256) NULL,
    `statusId` INT NOT NULL,
    PRIMARY KEY (`statusId`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TelephoneNumber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TelephoneNumber` (
                                                        `telephoneId` INT NOT NULL,
                                                        `countyCode` VARCHAR(256) NULL,
    `areaCode` VARCHAR(256) NULL,
    `cityCode` VARCHAR(256) NULL,
    `localNumber` VARCHAR(256) NULL,
    `ext` VARCHAR(256) NULL,
    `dialOut` VARCHAR(256) NULL,
    `internationalPhone` VARCHAR(256) NULL,
    `ituPhone` VARCHAR(256) NULL,
    PRIMARY KEY (`telephoneId`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
                                                 `UUID` INT NOT NULL,
                                                 `kind` VARCHAR(256) NULL,
    `specialNeed` VARCHAR(256) NULL,
    `vip` TINYINT NULL,
    `pucNumber` VARCHAR(256) NULL,
    `locale` VARCHAR(256) NULL,
    `customerName` VARCHAR(256) NULL,
    `status` INT NOT NULL,
    `TelephoneNumber_telephoneId` INT NOT NULL,
    `priorityRank` INT NULL,
    `priorityType` VARCHAR(256) NULL,
    `priorityJustification` VARCHAR(256) NULL,
    PRIMARY KEY (`UUID`),
    INDEX `fk_Customer_Status1_idx` (`status` ASC) VISIBLE,
    INDEX `fk_Customer_TelephoneNumber1_idx` (`TelephoneNumber_telephoneId` ASC) VISIBLE,
    CONSTRAINT `fk_Customer_Status1`
    FOREIGN KEY (`status`)
    REFERENCES `mydb`.`Status` (`statusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Customer_TelephoneNumber1`
    FOREIGN KEY (`TelephoneNumber_telephoneId`)
    REFERENCES `mydb`.`TelephoneNumber` (`telephoneId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EletronicAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EletronicAddress` (
                                                         `electronicAddressId` INT NOT NULL,
                                                         `lan` VARCHAR(256) NULL,
    `mac` VARCHAR(256) NULL,
    `email1` VARCHAR(256) NULL,
    `email2` VARCHAR(256) NULL,
    `web` VARCHAR(256) NULL,
    `raido` VARCHAR(256) NULL,
    `userID` VARCHAR(256) NULL,
    `password` VARCHAR(256) NULL,
    PRIMARY KEY (`electronicAddressId`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StreetAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StreetAddress` (
                                                      `streetAddressId` INT NOT NULL,
                                                      `streetNumber` VARCHAR(256) NULL,
    `streetName` VARCHAR(256) NULL,
    `streetSuffix` VARCHAR(256) NULL,
    `streetPrefix` VARCHAR(256) NULL,
    `streetType` VARCHAR(256) NULL,
    `streetCode` VARCHAR(256) NULL,
    `buildingName` VARCHAR(256) NULL,
    `suiteNumber` VARCHAR(256) NULL,
    `addressGeneral` VARCHAR(256) NULL,
    `addressGeneral2` VARCHAR(256) NULL,
    `addressGeneral3` VARCHAR(45) NULL,
    `withinTownLimits` TINYINT NULL,
    PRIMARY KEY (`streetAddressId`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organisation` (
                                                     `organizationId` INT NOT NULL,
                                                     `streetAddress` INT NULL,
                                                     `postalAddress` INT NULL,
                                                     `phone1` VARCHAR(256) NULL,
    `phone2` VARCHAR(256) NULL,
    `organisationName` VARCHAR(256) NULL,
    `electronicAddress` INT NOT NULL,
    `TelephoneNumber_telephoneId` INT NOT NULL,
    `StreetAddress_streetAddressId` INT NOT NULL,
    PRIMARY KEY (`organizationId`),
    INDEX `fk_Organisation_EletronicAddress1_idx` (`electronicAddress` ASC) VISIBLE,
    INDEX `fk_Organisation_TelephoneNumber1_idx` (`TelephoneNumber_telephoneId` ASC) VISIBLE,
    INDEX `fk_Organisation_StreetAddress1_idx` (`StreetAddress_streetAddressId` ASC) VISIBLE,
    CONSTRAINT `fk_Organisation_EletronicAddress1`
    FOREIGN KEY (`electronicAddress`)
    REFERENCES `mydb`.`EletronicAddress` (`electronicAddressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Organisation_TelephoneNumber1`
    FOREIGN KEY (`TelephoneNumber_telephoneId`)
    REFERENCES `mydb`.`TelephoneNumber` (`telephoneId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Organisation_StreetAddress1`
    FOREIGN KEY (`StreetAddress_streetAddressId`)
    REFERENCES `mydb`.`StreetAddress` (`streetAddressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomerAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CustomerAccount` (
    `accountId` VARCHAR(256) NOT NULL,
    `billingCycle` VARCHAR(256) NULL,
    `lastBillAmount` INT NULL,
    `UUID` INT NOT NULL,
    `Organisation_organizationId` INT NOT NULL,
    PRIMARY KEY (`accountId`),
    INDEX `fk_CustomerAccount_Customer_idx` (`UUID` ASC) VISIBLE,
    INDEX `fk_CustomerAccount_Organisation1_idx` (`Organisation_organizationId` ASC) VISIBLE,
    CONSTRAINT `fk_CustomerAccount_Customer`
    FOREIGN KEY (`UUID`)
    REFERENCES `mydb`.`Customer` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_CustomerAccount_Organisation1`
    FOREIGN KEY (`Organisation_organizationId`)
    REFERENCES `mydb`.`Organisation` (`organizationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomerAgreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CustomerAgreement` (
                                                          `agreementId` INT NOT NULL,
                                                          `loadMgmt` VARCHAR(256) NULL,
    `isPrePay` TINYINT NULL,
    `shutOffDateTime` DATETIME NULL,
    `DemandResponseProgram` VARCHAR(256) NULL,
    `PricingStructures` VARCHAR(256) NULL,
    `currency` VARCHAR(256) NULL,
    `futureStatus` VARCHAR(256) NULL,
    `accountId` VARCHAR(256) NOT NULL,
    PRIMARY KEY (`agreementId`),
    INDEX `fk_CustomerAgreement_CustomerAccount1_idx` (`accountId` ASC) VISIBLE,
    CONSTRAINT `fk_CustomerAgreement_CustomerAccount1`
    FOREIGN KEY (`accountId`)
    REFERENCES `mydb`.`CustomerAccount` (`accountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
                                                 `locationId` INT NOT NULL,
                                                 `type` VARCHAR(256) NULL,
    `mainAddress` VARCHAR(256) NULL,
    `secondaryAddress` VARCHAR(256) NULL,
    `phone1` VARCHAR(256) NULL,
    `phone2` VARCHAR(256) NULL,
    `electronicAddress` VARCHAR(256) NULL,
    `geoInfoReference` VARCHAR(256) NULL,
    `direction` VARCHAR(256) NULL,
    `status` INT NOT NULL,
    `EletronicAddress_electronicAddressId` INT NOT NULL,
    `StreetAddress_streetAddressId` INT NOT NULL,
    PRIMARY KEY (`locationId`),
    INDEX `fk_Location_Status1_idx` (`status` ASC) INVISIBLE,
    INDEX `fk_Location_EletronicAddress1_idx` (`EletronicAddress_electronicAddressId` ASC) VISIBLE,
    INDEX `fk_Location_StreetAddress1_idx` (`StreetAddress_streetAddressId` ASC) VISIBLE,
    CONSTRAINT `fk_Location_Status1`
    FOREIGN KEY (`status`)
    REFERENCES `mydb`.`Status` (`statusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Location_EletronicAddress1`
    FOREIGN KEY (`EletronicAddress_electronicAddressId`)
    REFERENCES `mydb`.`EletronicAddress` (`electronicAddressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Location_StreetAddress1`
    FOREIGN KEY (`StreetAddress_streetAddressId`)
    REFERENCES `mydb`.`StreetAddress` (`streetAddressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ServiceLocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ServiceLocation` (
                                                        `serviceId` INT NOT NULL,
                                                        `accessMethod` VARCHAR(256) NULL,
    `siteAccessProblem` VARCHAR(256) NULL,
    `needsInspection` TINYINT NULL,
    `UsagePointsURL` VARCHAR(256) NULL,
    `outageBlock` VARCHAR(256) NULL,
    `CustomerAgreement_agreementId` INT NOT NULL,
    `Location_locationId` INT NOT NULL,
    PRIMARY KEY (`serviceId`, `CustomerAgreement_agreementId`, `Location_locationId`),
    INDEX `fk_ServiceLocation_CustomerAgreement1_idx` (`CustomerAgreement_agreementId` ASC) VISIBLE,
    INDEX `fk_ServiceLocation_Location1_idx` (`Location_locationId` ASC) VISIBLE,
    CONSTRAINT `fk_ServiceLocation_CustomerAgreement1`
    FOREIGN KEY (`CustomerAgreement_agreementId`)
    REFERENCES `mydb`.`CustomerAgreement` (`agreementId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_ServiceLocation_Location1`
    FOREIGN KEY (`Location_locationId`)
    REFERENCES `mydb`.`Location` (`locationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asset` (
                                              `assetId` INT NOT NULL,
                                              `type` VARCHAR(256) NULL,
    `utcNumber` VARCHAR(256) NULL,
    `serialNumber` VARCHAR(256) NULL,
    `lotNumber` VARCHAR(256) NULL,
    `purchasePrice` VARCHAR(256) NULL,
    `critical` TINYINT NULL,
    `eletronicAddress` INT NOT NULL,
    `lifecycle` VARCHAR(256) NULL,
    `initalCondition` VARCHAR(256) NULL,
    `initialLossOfLife` VARCHAR(256) NULL,
    `status` INT NOT NULL,
    `acceptanceType` VARCHAR(256) NULL,
    `acceptanceSuccess` TINYINT NULL,
    `acceptanceDateTime` DATETIME NULL,
    `manufacturedDate` DATETIME NULL,
    `purchaseDate` DATETIME NULL,
    `receivedDate` DATETIME NULL,
    `installationDate` DATETIME NULL,
    `removalDate` DATETIME NULL,
    `retiredDate` DATETIME NULL,
    PRIMARY KEY (`assetId`),
    INDEX `fk_electronicAddress` (`eletronicAddress` ASC) INVISIBLE,
    INDEX `fk_status` (`status` ASC) VISIBLE,
    CONSTRAINT `fk_eletronicAddress`
    FOREIGN KEY (`eletronicAddress`)
    REFERENCES `mydb`.`EletronicAddress` (`electronicAddressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_status`
    FOREIGN KEY (`status`)
    REFERENCES `mydb`.`Status` (`statusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Meter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Meter` (
                                              `meterId` INT NOT NULL,
                                              `formNumber` VARCHAR(256) NULL,
    `MeterMultiplier` VARCHAR(256) NULL,
    `IntervalLength` VARCHAR(256) NULL,
    `ServiceLocation_serviceId` INT NOT NULL,
    `Asset_assetId` INT NOT NULL,
    PRIMARY KEY (`meterId`, `ServiceLocation_serviceId`, `Asset_assetId`),
    INDEX `fk_Meter_ServiceLocation1_idx` (`ServiceLocation_serviceId` ASC) VISIBLE,
    INDEX `fk_Meter_Asset1_idx` (`Asset_assetId` ASC) VISIBLE,
    CONSTRAINT `fk_Meter_ServiceLocation1`
    FOREIGN KEY (`ServiceLocation_serviceId`)
    REFERENCES `mydb`.`ServiceLocation` (`serviceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Meter_Asset1`
    FOREIGN KEY (`Asset_assetId`)
    REFERENCES `mydb`.`Asset` (`assetId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ServiceSupplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ServiceSupplier` (
                                                        `serviceSupplierId` INT NOT NULL,
                                                        `kind` VARCHAR(256) NULL,
    `issuerIdentificationNumber` VARCHAR(256) NULL,
    `effectiveDate` DATETIME NULL,
    PRIMARY KEY (`serviceSupplierId`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Document` (
                                                 `documentId` INT NOT NULL,
                                                 `type` VARCHAR(256) NULL,
    `authorName` VARCHAR(256) NULL,
    `createdDateTime` DATETIME NULL,
    `lastModifiedDateTime` DATETIME NULL,
    `revisionNumber` VARCHAR(256) NULL,
    `subject` VARCHAR(256) NULL,
    `title` VARCHAR(256) NULL,
    `comment` VARCHAR(256) NULL,
    `electronicAddress` INT NOT NULL,
    `docStatus` INT NOT NULL,
    PRIMARY KEY (`documentId`),
    INDEX `fk_Document_EletronicAddress1_idx` (`electronicAddress` ASC) VISIBLE,
    INDEX `fk_Document_Status1_idx` (`docStatus` ASC) VISIBLE,
    CONSTRAINT `fk_Document_EletronicAddress1`
    FOREIGN KEY (`electronicAddress`)
    REFERENCES `mydb`.`EletronicAddress` (`electronicAddressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Document_Status1`
    FOREIGN KEY (`docStatus`)
    REFERENCES `mydb`.`Status` (`statusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AccountNotification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AccountNotification` (
                                                            `notificationId` INT NOT NULL,
                                                            `methodKind` VARCHAR(256) NULL,
    `time` DATETIME NULL,
    `note` VARCHAR(256) NULL,
    `customerNotificationKind` VARCHAR(256) NULL,
    `accountId` VARCHAR(256) NOT NULL,
    PRIMARY KEY (`notificationId`, `accountId`),
    INDEX `fk_AccountNotification_CustomerAccount1_idx` (`accountId` ASC) VISIBLE,
    CONSTRAINT `fk_AccountNotification_CustomerAccount1`
    FOREIGN KEY (`accountId`)
    REFERENCES `mydb`.`CustomerAccount` (`accountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EndDevice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EndDevice` (
                                                  `endDeviceId` INT NOT NULL,
                                                  `isVirtual` TINYINT NULL,
                                                  `isPan` TINYINT NULL,
                                                  `installCode` VARCHAR(256) NULL,
    `amrSystem` VARCHAR(256) NULL,
    `ServiceLocation_serviceId` INT NOT NULL,
    `Asset_assetId` INT NOT NULL,
    PRIMARY KEY (`ServiceLocation_serviceId`, `Asset_assetId`, `endDeviceId`),
    INDEX `fk_EndDevice_ServiceLocation1_idx` (`ServiceLocation_serviceId` ASC) VISIBLE,
    INDEX `fk_EndDevice_Asset1_idx` (`Asset_assetId` ASC) VISIBLE,
    CONSTRAINT `fk_EndDevice_ServiceLocation1`
    FOREIGN KEY (`ServiceLocation_serviceId`)
    REFERENCES `mydb`.`ServiceLocation` (`serviceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_EndDevice_Asset1`
    FOREIGN KEY (`Asset_assetId`)
    REFERENCES `mydb`.`Asset` (`assetId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TimeConfiguration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TimeConfiguration` (
                                                          `Customer_UUID` INT NOT NULL,
                                                          `timeConfiguration` VARCHAR(256) NULL,
    PRIMARY KEY (`Customer_UUID`),
    CONSTRAINT `fk_TimeConfiguration_Customer1`
    FOREIGN KEY (`Customer_UUID`)
    REFERENCES `mydb`.`Customer` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
