CREATE TABLE IF NOT EXISTS usage.usage_summaries (
  description TEXT,
  published TIMESTAMP,
  self_link_href TEXT,
  self_link_rel TEXT,
  up_link_href TEXT,
  up_link_rel TEXT,
  updated TIMESTAMP,
  uuid UUID PRIMARY KEY NOT NULL,
  bill_last_period BIGINT,
  bill_to_date BIGINT,
  billing_period_duration BIGINT,
  billing_period_start BIGINT,
  cost_additional_last_period BIGINT,
  currency TEXT,
  current_billing_period_overall_consumption_power_ten_multiplier TEXT,
  current_billing_period_overall_consumption_timestamp BIGINT,
  current_billing_period_overall_consumption_uom TEXT,
  current_billing_period_overall_consumption_value BIGINT,
  current_day_last_year_net_consumption_power_of_ten_multiplier TEXT,
  current_day_last_year_net_consumption_timestamp BIGINT,
  current_day_last_year_net_consumption_uom TEXT,
  current_day_last_year_net_consumption_value BIGINT,
  current_day_net_consumption_power_of_ten_multiplier TEXT,
  current_day_net_consumption_timeStamp BIGINT,
  current_day_net_consumption_uom TEXT,
  current_day_net_consumption_value BIGINT,
  current_day_overall_consumption_power_of_ten_multiplier TEXT,
  current_day_overall_consumption_timestamp BIGINT,
  current_day_overall_consumption_uom TEXT,
  current_day_overall_consumption_value BIGINT,
  overall_consumption_last_period_power_of_ten_multiplier TEXT,
  overall_consumption_last_period_timestamp BIGINT,
  overall_consumption_last_period_uom TEXT,
  overall_consumption_last_period_value BIGINT,
  peak_demand_power_of_ten_multiplier TEXT,
  peak_demand_timestamp BIGINT,
  peak_demand_uom TEXT,
  peak_demand_value BIGINT,
  previous_day_last_year_overall_consumption_power_ten_multiplier TEXT,
  previous_day_last_year_overall_consumption_timestamp BIGINT,
  previous_day_last_year_overall_consumption_uom TEXT,
  previous_day_last_year_overall_consumption_value BIGINT,
  previous_day_net_consumption_power_of_ten_multiplier TEXT,
  previous_day_net_consumption_timestamp BIGINT,
  previous_day_net_consumption_uom TEXT,
  previous_day_net_consumption_value BIGINT,
  previous_day_overall_consumption_power_of_ten_multiplier TEXT,
  previous_day_overall_consumption_timestamp BIGINT,
  previous_day_overall_consumption_uom TEXT,
  previous_day_overall_consumption_value BIGINT,
  quality_of_reading TEXT,
  ratchet_demand_power_of_ten_multiplier TEXT,
  ratchet_demand_timestamp BIGINT,
  ratchet_demand_uom TEXT,
  ratchet_demand_value BIGINT,
  ratchet_demand_period_duration BIGINT,
  ratchet_demand_period_start BIGINT,
  status_timestamp BIGINT NOT NULL
--   TODO add reference to usage_points uuid EX: usage_point_uuid UUID NOT NULL REFERENCES usage.usage_points ON DELETE CASCADE
  );

CREATE TABLE IF NOT EXISTS usage.line_item (
  amount BIGINT NOT NULL,
  date_time BIGINT NOT NULL,
  note TEXT,
  rounding BIGINT,
  usage_summary_uuid UUID NOT NULL REFERENCES usage.usage_summaries ON DELETE CASCADE
);
